// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repetitio.Infrastructure.Persistence;

#nullable disable

namespace Repetitio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepetitioDbContext))]
    [Migration("20260830152442_AddDsaTracker")]
    partial class AddDsaTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approach")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Assumptions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedSpaceComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedTimeComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeChecklist")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MissedMentalSteps")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemStatement")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionsToAsk")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCases")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId");

                    b.ToTable("DsaProblems");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaceComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.ToTable("DsaSolutions");
                });

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LearningItemId");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LearningItemTags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithOne()
                        .HasForeignKey("Repetitio.Domain.Dsa.DsaProblem", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaSolution", b =>
                {
                    b.HasOne("Repetitio.Domain.Dsa.DsaProblem", "Problem")
                        .WithMany("Solutions")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("Tags")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repetitio.Domain.Tags.Tag", "Tag")
                        .WithMany("LearningItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Navigation("PracticeSessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Navigation("LearningItems");
                });
#pragma warning restore 612, 618
        }
    }
}
