// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repetitio.Infrastructure.Persistence;

#nullable disable

namespace Repetitio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepetitioDbContext))]
    [Migration("20260831112612_AddNotes")]
    partial class AddNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approach")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Assumptions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedSpaceComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedTimeComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeChecklist")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MissedMentalSteps")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemStatement")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionsToAsk")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCases")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId");

                    b.ToTable("DsaProblems");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaSolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaceComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeComplexity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningItemId");

                    b.ToTable("DsaSolutions");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.Flashcard", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultSessionSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("NextReviewAt");

                    b.ToTable("FlashcardDecks");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardDeckCard", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlashcardLearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId", "FlashcardLearningItemId");

                    b.HasIndex("FlashcardLearningItemId");

                    b.ToTable("FlashcardDeckCards");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlashcardLearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("KnewAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("FlashcardLearningItemId");

                    b.HasIndex("PracticeSessionId")
                        .IsUnique();

                    b.ToTable("FlashcardReviews");
                });

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("Repetitio.Domain.Notes.NotePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Area");

                    b.HasIndex("Area", "SortOrder");

                    b.ToTable("NotePages");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LearningItemId");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("Repetitio.Domain.SystemDesign.SystemDesignProblem", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiDesignMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchitectureMarkdown")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapacityEstimatesMarkdown")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstraintsMarkdown")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataModelMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionalRequirementsMarkdown")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NonFunctionalRequirementsMarkdown")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReflectionMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScalingStrategyMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeoffsMarkdown")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId");

                    b.ToTable("SystemDesignProblems");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LearningItemTags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithOne()
                        .HasForeignKey("Repetitio.Domain.Dsa.DsaProblem", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaSolution", b =>
                {
                    b.HasOne("Repetitio.Domain.Dsa.DsaProblem", "Problem")
                        .WithMany("Solutions")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.Flashcard", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithOne()
                        .HasForeignKey("Repetitio.Domain.Flashcards.Flashcard", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardDeckCard", b =>
                {
                    b.HasOne("Repetitio.Domain.Flashcards.FlashcardDeck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repetitio.Domain.Flashcards.Flashcard", "Flashcard")
                        .WithMany("DeckCards")
                        .HasForeignKey("FlashcardLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardReview", b =>
                {
                    b.HasOne("Repetitio.Domain.Flashcards.FlashcardDeck", "Deck")
                        .WithMany("Reviews")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Repetitio.Domain.Flashcards.Flashcard", "Flashcard")
                        .WithMany("Reviews")
                        .HasForeignKey("FlashcardLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repetitio.Domain.Practice.PracticeSession", "PracticeSession")
                        .WithOne()
                        .HasForeignKey("Repetitio.Domain.Flashcards.FlashcardReview", "PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Flashcard");

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.SystemDesign.SystemDesignProblem", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithOne()
                        .HasForeignKey("Repetitio.Domain.SystemDesign.SystemDesignProblem", "LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("Tags")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repetitio.Domain.Tags.Tag", "Tag")
                        .WithMany("LearningItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Repetitio.Domain.Dsa.DsaProblem", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.Flashcard", b =>
                {
                    b.Navigation("DeckCards");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Repetitio.Domain.Flashcards.FlashcardDeck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Navigation("PracticeSessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Navigation("LearningItems");
                });
#pragma warning restore 612, 618
        }
    }
}
