// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repetitio.Infrastructure.Persistence;

#nullable disable

namespace Repetitio.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Represents the Entity Framework model snapshot for the Repetitio database.
    /// </summary>
    [DbContext(typeof(RepetitioDbContext))]
    partial class RepetitioDbContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// Builds the current model snapshot.
        /// </summary>
        /// <param name="modelBuilder">The model builder.</param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("LearningItems");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImproveNext")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatHelped")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatWasDifficult")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LearningItemId");

                    b.ToTable("PracticeSessions");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.Property<Guid>("LearningItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("LearningItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LearningItemTags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Practice.PracticeSession", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.LearningItemTag", b =>
                {
                    b.HasOne("Repetitio.Domain.LearningItems.LearningItem", "LearningItem")
                        .WithMany("Tags")
                        .HasForeignKey("LearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repetitio.Domain.Tags.Tag", "Tag")
                        .WithMany("LearningItems")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Repetitio.Domain.LearningItems.LearningItem", b =>
                {
                    b.Navigation("PracticeSessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Repetitio.Domain.Tags.Tag", b =>
                {
                    b.Navigation("LearningItems");
                });
#pragma warning restore 612, 618
        }
    }
}
